export const SUPPORTED_CONNECTORS = [
  {
    id: '1',
    name: 'Snowflake',
    description: 'Connect your Snowflake data warehouse for instant AI analysis',
    type: 'Data Warehouse',
    icon: 'database',
    status: 'disconnected',
  },
  {
    id: '2',
    name: 'MySQL',
    description: 'Connect your MySQL database for instant AI analysis',
    type: 'Database',
    icon: 'server',
    status: 'disconnected',
  },
  {
    id: '3',
    name: 'MSSQL',
    description: 'Connect your Microsoft SQL Server for instant AI analysis',
    type: 'Database',
    icon: 'server',
    status: 'disconnected',
  },
  {
    id: '4',
    name: 'PostgreSQL',
    description: 'Connect your PostgreSQL database for instant AI analysis',
    type: 'Database',
    icon: 'database',
    status: 'disconnected',
  },
  {
    id: '5',
    name: 'Google Sheets',
    description: 'Connect your Google Sheets to query and analyze spreadsheet data with AI',
    type: 'Integration',
    icon: 'table',
    status: 'disconnected',
  },
  {
    id: '6',
    name: 'Web Search using LLM',
    description: 'Query the web using large language models to fetch and analyze live data',
    type: 'Integration',
    icon: 'globe',
    status: 'disconnected',
  },
];
